version: '3.7'

services:
  ### PHP ##############################################
  php-fpm:
    build: ./php
    container_name: php-fpm
    # privileged: true
    volumes:
      - ./workspace:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  ### Nginx ##############################################
  nginx:
    image: nginx:1.17.3-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.template:/etc/nginx/conf.d/nginx.template
      - ./workspace:/var/www/html
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
      - PHP_APP_HOST=php-fpm
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  ### MySQL ##############################################
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --local-infile=1
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
  ### Redis ##############################################
  redis:
    image: redis:5.0.5
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
