version: "3.7"

services:
  ### PHP ##############################################
  php-fpm:
    build: ./php
    container_name: php-fpm
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./workspace:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  ### Nginx ##############################################
  nginx:
    image: nginx:1.17.9-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/ssl:/etc/nginx/ssl
      - ./workspace:/var/www/html
    environment:
      - PHP_APP_HOST=php-fpm
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  ### MySQL ##############################################
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  ### Redis ##############################################
  redis:
    image: redis:5.0.5
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
